a = " Chocolate Chip Snickerdoodle Cake\nPrep Time 10 mins\nCook Time 30 mins\nTotal Time 40 mins\nServings 9 servings\nYield 1 (8x8-inch) cake\n\n“Snacking Bakes” Copyright © 2023 by Yasameen Arefi-Afshar. Published by Clarkson Potter, an imprint of Crown Publishing Group, a division of Penguin Random House LLC, New York.\nIngredients\n\n    3/4 cup (150g) plus 2 tablespoons granulated sugar\n\n    1 teaspoon ground cinnamon\n\n    2 large eggs\n\n    3/4 cup (173g) sour cream\n\n    1/2 cup (95g) neutral oil\n\n    1/2 teaspoon fine sea salt\n\n    1 1/2 teaspoons baking powder\n\n    1/2 teaspoon baking soda\n\n    1 3/4 cups (225g) all-purpose flour\n\n    1/2 cup (85g) semisweet chocolate chips\n\nMethod\n\n    Position a rack in the center of the oven and preheat to 350ºF. Coat an 8×8-inch baking pan with cooking spray or brush with butter. Line the pan with a strip of parchment paper that hangs over two of the edges. Very lightly butter or spray the parchment.\n\n    In a small bowl, combine 2 tablespoons of the sugar and the cinnamon. Sprinkle the bottom and sides of the pan with half of the cinnamon- sugar mixture.\n\n    In a large bowl, whisk together the remaining 3/4 cup (150g) sugar and eggs until pale and foamy, about 1 minute. Add the sour cream, oil, and salt and whisk until smooth and emulsified.\n\n    Whisk in the baking powder and baking soda. Fold in the flour and chocolate chips with a spatula and mix until well combined.\n\n    Pour the batter into the prepared pan, smooth the top, and sprinkle the remaining cinnamon sugar over the top.\n\n    Bake the cake until puffed and golden and a tester inserted into the center comes out clean or with a bit of melted chocolate, 30 to 40 minutes.\n\n    Let the cake cool in the pan on a rack for about 15 minutes, then use the parchment paper to lift the cake out of the pan and onto the rack to cool. Store loosely covered at room temperature for up to 3 days"
a = a.split("\n")
s = []
for i in a:
    i = i + "<br/>"
    s.append(i)

s = "".join(s)
print(s)
# " Chocolate Chip Snickerdoodle Cake\nPrep Time 10 mins\nCook Time 30 mins\nTotal Time 40 mins\nServings 9 servings\nYield 1 (8x8-inch) cake\n\n“Snacking Bakes” Copyright © 2023 by Yasameen Arefi-Afshar. Published by Clarkson Potter, an imprint of Crown Publishing Group, a division of Penguin Random House LLC, New York.\nIngredients\n\n    3/4 cup (150g) plus 2 tablespoons granulated sugar\n\n    1 teaspoon ground cinnamon\n\n    2 large eggs\n\n    3/4 cup (173g) sour cream\n\n    1/2 cup (95g) neutral oil\n\n    1/2 teaspoon fine sea salt\n\n    1 1/2 teaspoons baking powder\n\n    1/2 teaspoon baking soda\n\n    1 3/4 cups (225g) all-purpose flour\n\n    1/2 cup (85g) semisweet chocolate chips\n\nMethod\n\n    Position a rack in the center of the oven and preheat to 350ºF. Coat an 8×8-inch baking pan with cooking spray or brush with butter. Line the pan with a strip of parchment paper that hangs over two of the edges. Very lightly butter or spray the parchment.\n\n    In a small bowl, combine 2 tablespoons of the sugar and the cinnamon. Sprinkle the bottom and sides of the pan with half of the cinnamon- sugar mixture.\n\n    In a large bowl, whisk together the remaining 3/4 cup (150g) sugar and eggs until pale and foamy, about 1 minute. Add the sour cream, oil, and salt and whisk until smooth and emulsified.\n\n    Whisk in the baking powder and baking soda. Fold in the flour and chocolate chips with a spatula and mix until well combined.\n\n    Pour the batter into the prepared pan, smooth the top, and sprinkle the remaining cinnamon sugar over the top.\n\n    Bake the cake until puffed and golden and a tester inserted into the center comes out clean or with a bit of melted chocolate, 30 to 40 minutes.\n\n    Let the cake cool in the pan on a rack for about 15 minutes, then use the parchment paper to lift the cake out of the pan and onto the rack to cool. Store loosely covered at room temperature for up to 3 days"
